collections:
  codekata:
    output: true
    permalink: /codekata/:name/
  analysis:
    output: true
    permalink: /analysis/:name/
    
  sql_kr:
    output: true 
  sql_us:
    output: true
  sql_cn:
    output: true

defaults:
  - scope:
      path: ""
      type: codekata
    values:
      layout: post
      category: Code Kata
