collections:
  codekata:
    output: true
    permalink: /codekata/:name/
  analysis:
    output: true
    permalink: /analysis/:name/
  sql_kr:
    output: true
    permalink: /sql-study/kr/:name/
  sql_us:
    output: true
    permalink: /sql-study/us/:name/
  sql_cn:
    output: true
    permalink: /sql-study/cn/:name/

defaults:
  - scope:
      path: ""
      type: codekata
    values:
      layout: post
      category: Code Kata
