collections:
  codekata:
    output: true
    permalink: /codekata/:name/
  analysis:
    output: true
    permalink: /analysis/:name/

defaults:
  - scope:
      path: ""
      type: codekata
    values:
      layout: post
      category: Code Kata
